<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="HDC3-L-4B4PLC2" name="com.automation.bms.NewTest" tests="7" failures="1" timestamp="24 May 2018 10:40:29 GMT" time="0.030" errors="0">
  <testcase name="f2" time="0.002" classname="com.automation.bms.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.automation.bms.NewTest.f2(NewTest.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- f2 -->
  <testcase name="f1" time="0.012" classname="com.automation.bms.NewTest"/>
  <testcase name="f2" time="0.009" classname="com.automation.bms.NewTest">
    <skipped/>
  </testcase> <!-- f2 -->
  <testcase name="f2" time="0.002" classname="com.automation.bms.NewTest">
    <skipped/>
  </testcase> <!-- f2 -->
  <testcase name="f2" time="0.001" classname="com.automation.bms.NewTest">
    <skipped/>
  </testcase> <!-- f2 -->
  <testcase name="f2" time="0.003" classname="com.automation.bms.NewTest">
    <skipped/>
  </testcase> <!-- f2 -->
  <testcase name="f2" time="0.001" classname="com.automation.bms.NewTest">
    <skipped/>
  </testcase> <!-- f2 -->
</testsuite> <!-- com.automation.bms.NewTest -->
